/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomesRouteImport } from './routes/homes'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as HomesOrgIdRouteImport } from './routes/homes.$orgId'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard.settings.organization'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesRoute = HomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const HomesOrgIdRoute = HomesOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => HomesRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/guide': typeof GuideRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/homes/$orgId': typeof HomesOrgIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guide': typeof GuideRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/homes/$orgId': typeof HomesOrgIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/guide': typeof GuideRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/homes/$orgId': typeof HomesOrgIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/guide'
    | '/homes'
    | '/login'
    | '/register'
    | '/dashboard/profile'
    | '/homes/$orgId'
    | '/dashboard/'
    | '/dashboard/settings/organization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guide'
    | '/homes'
    | '/login'
    | '/register'
    | '/dashboard/profile'
    | '/homes/$orgId'
    | '/dashboard'
    | '/dashboard/settings/organization'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/guide'
    | '/homes'
    | '/login'
    | '/register'
    | '/dashboard/profile'
    | '/homes/$orgId'
    | '/dashboard/'
    | '/dashboard/settings/organization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GuideRoute: typeof GuideRoute
  HomesRoute: typeof HomesRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes': {
      id: '/homes'
      path: '/homes'
      fullPath: '/homes'
      preLoaderRoute: typeof HomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/homes/$orgId': {
      id: '/homes/$orgId'
      path: '/$orgId'
      fullPath: '/homes/$orgId'
      preLoaderRoute: typeof HomesOrgIdRouteImport
      parentRoute: typeof HomesRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/settings/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HomesRouteChildren {
  HomesOrgIdRoute: typeof HomesOrgIdRoute
}

const HomesRouteChildren: HomesRouteChildren = {
  HomesOrgIdRoute: HomesOrgIdRoute,
}

const HomesRouteWithChildren = HomesRoute._addFileChildren(HomesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GuideRoute: GuideRoute,
  HomesRoute: HomesRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
